<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "link".
 *
 * @property int $id
 * @property int $user_id
 * @property string $link
 * @property string $original_link
 * @property int $count_usage
 * @property string $created_at
 *
 * @property User $user
 */
class Link extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'link';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['user_id', 'link', 'original_link'], 'required'],
            [['user_id', 'count_usage'], 'integer'],
            [['original_link'], 'string'],
            [['created_at'], 'safe'],
            [['link'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['user_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'user_id' => 'User ID',
            'link' => 'Link',
            'original_link' => 'Original Link',
            'count_usage' => 'Count Usage',
            'created_at' => 'Created At',
        ];
    }

    public function beforeValidate()
    {
        if($this->isNewRecord){
            $this->user_id = Yii::$app->user->id;
        }
        return parent::beforeValidate(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    /**
     * Проверка существования ссылки в базе данных
     * @param $url
     * @return bool
     */
    public static function checkExistLinkByUrl($url)
    {
        $model = self::find()->where(['original_link'=>$url])->one();
        if(!$model){
            $model = new Link();
            $model->link = uniqid();//$this->generateShortLink($url);
            $model->original_link = $url;
            if($model->save()){
                return $model->link;
            }
            return $model->getErrors();
        }
        return $model->link;
    }
}
